### ISSUE TITLE
project preparation, briefing and kickoff

### ISSUE THREAD

**Issue by serapath** [playproject-io/dat-ecosystem.github.io#2]
## `@todo`
* [ ] finish project brief, preparation and kickoff
  * [x] make entire project plan
  * [x] skim all input resources for the project
  * [x] group input resources into project categories
  * [x] assign all input resources as inputs to specific tasks 
  * [ ] study entire project plan
    * `@input`❓`project brief screencast`
  * [ ] ask questions, get answers and discuss in comments to become familiar with the project
  * [ ] estimate every task in the project outline using planning poker and send results to us **privately**
    * `@input` :package: [`planning poker cards picture`](https://www.visual-paradigm.com/servlet/editor-content/scrum/what-is-agile-planning-poker/sites/7/2018/12/fibonacci-sequence-and-planning-poker.png)
    * `@output` :question: `final outline with consensus time estimations of all tasks`
  * [ ] update project plan with estimation consensus values
    * `@input` :question: `final outline with consensus time estimations of all tasks`
    * `@output` :question: [`updated plan with estimations`](https://github.com/playproject-io/dat-ecosystem.github.io/issues/1)

---

## `@info`
...
