### ISSUE TITLE
make component system

### ISSUE THREAD

**Issue by serapath** [playproject-io/dat-ecosystem.github.io#3]
## `@todo`
* [ ] develop all sub sub components
  * [ ] #11
  * [ ] #12
  * [ ] #13
* [ ] develop `website/webapp` component
  * [ ] requirements gathering / UX survey
    1. user requirement / user research (interview, stories, task flow) + study previous features + competition
    2. product purpose/features/functionalities/behavior  (from users/stakeholders)
  * [ ] user journey/funnel
  * [ ] information architecture (content preparation)
  * [ ] design & prototype UI/UX (wireframes/designs)
  * [ ] component implementation
  * [ ] component preview page
  * [ ] component moodboards
  * [ ] component high-fidelity UI/UX themes
  * [ ] component testing (cross platform + devices)
  * [ ] present to validate
  * [ ] component refinement

---

## `@info`

develop a component for the entire dat-ecosystem website/webapp, which includes many sub components, each with many phases that can be worked on to some degree in parallel.
