### ISSUE TITLE
present & refine website/webapp to dat-ecosystem consortium

### ISSUE THREAD

**Issue by serapath** [playproject-io/dat-ecosystem.github.io#6]
## `@todo`
* [ ] present & refine website/webapp to dat-ecosystem consortium
  * [ ] record 3-5 minutes screencast to present a walkthrough of results
    * `@input` :question: `dat-ecosystem theme`
    * `@input` :question: `dat-ecosystem github webpage`
    * `@input` :question: [`updated playproject website repo`](https://github.com/playproject-io/playproject-io.github.io)
    * `@input` :question: [`update playproject website with dat-ecosystem section`](https://playproject.io/)
    * `@output` :question: `recorded 3-5 minutes screencast(s) presentation` 
  * [ ] present to get feedback
    * `@input` :question: `recorded 3-5 minutes screencast(s) presentation` 
    * `@output` :question: `presentation feedback document`
  * [ ] refine product content and wireframing based on feedback
    * `@input` :question: `dat-ecosystem theme`
    * `@input` :question: `dat-ecosystem github webpage`
    * `@input` :question: [`updated playproject website repo`](https://github.com/playproject-io/playproject-io.github.io)
    * `@input` :question: [`update playproject website with dat-ecosystem section`](https://playproject.io/)
    * `@output` :question: :checkered_flag: [`refined & accepted updated playproject website repo`](https://github.com/playproject-io/playproject-io.github.io)
    * `@output` :question: :checkered_flag: [`refined & accepted update playproject website with dat-ecosystem section`](https://playproject.io/)

---

## `@info`
...
