### ISSUE TITLE
create custom data (theme & content)

### ISSUE THREAD

**Issue by serapath** [playproject-io/dat-ecosystem.github.io#9]
## `@todo`
* [ ] create and choose moodboards
* [ ] create high-fidelity dat-ecosystem theme
* [ ] create content files in supported languages

---

## `@info`

Design one or more high fidelity wizardamigos themes, including colors and fonts and graphics and icons and whatever is necessary to be later applied to the design system and website/webapp
